
import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
import { getFirestore, doc, getDoc, setDoc, deleteDoc, collection, getDocs, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
import { firebaseConfig, EXAM_ID } from "./firebase-config.js";

const SECTIONS=[{"name": "Español I", "start": 1, "end": 9, "type": "esp"}, {"name": "Matemáticas I", "start": 10, "end": 30, "type": "mat"}, {"name": "Español II", "start": 31, "end": 47, "type": "esp"}, {"name": "Matemáticas II", "start": 48, "end": 67, "type": "mat"}, {"name": "Español III", "start": 68, "end": 82, "type": "esp"}, {"name": "Matemáticas III", "start": 83, "end": 102, "type": "mat"}, {"name": "Español IV", "start": 103, "end": 111, "type": "esp"}];
const PAGE_FILES=[];
const TOTAL_PAGES=35;
const TOTAL=111,LETTERS=['A','B','C','D'],TEACHER_PASS='valenciana2026';
const SPANISH_RANGES=[[1,9],[31,47],[68,82],[103,111]];
const MATH_RANGES=[[10,30],[48,67],[83,102]];
let currentQ=parseInt(localStorage.getItem('cv_current_q')||'1',10);
let currentPage=parseInt(localStorage.getItem('cv_current_page')||'1',10);
let zoom=parseFloat(localStorage.getItem('cv_zoom')||'1');
let responses=JSON.parse(localStorage.getItem('cv_responses')||'{}');
let key={"1": "B", "2": "C", "3": "C", "4": "D", "5": "B", "6": "A", "7": "B", "8": "D", "9": "B", "10": "A", "11": "A", "12": "A", "13": "D", "14": "B", "15": "C", "16": "A", "17": "C", "18": "C", "19": "B", "20": "C", "21": "B", "22": "B", "23": "D", "24": "A", "25": "A", "26": "D", "27": "D", "28": "B", "29": "D", "30": "B", "31": "D", "32": "B", "33": "A", "34": "A", "35": "D", "36": "B", "37": "B", "38": "D", "39": "C", "40": "A", "41": "C", "42": "D", "43": "B", "44": "C", "45": "D", "46": "A", "47": "A", "48": "B", "49": "A", "50": "A", "51": "D", "52": "C", "53": "A", "54": "B", "55": "C", "56": "A", "57": "C", "58": "A", "59": "C", "60": "A", "61": "D", "62": "C", "63": "D", "64": "A", "65": "C", "66": "C", "67": "B", "68": "D", "69": "B", "70": "A", "71": "D", "72": "B", "73": "C", "74": "A", "75": "D", "76": "D", "77": "A", "78": "D", "79": "C", "80": "B", "81": "D", "82": "A", "83": "B", "84": "B", "85": "B", "86": "D", "87": "A", "88": "C", "89": "C", "90": "B", "91": "B", "92": "C", "93": "A", "94": "D", "95": "B", "96": "C", "97": "A", "98": "C", "99": "D", "100": "C", "101": "C", "102": "C", "103": "D", "104": "D", "105": "C", "106": "D", "107": "B", "108": "B", "109": "C", "110": "B", "111": "C"};
let results=JSON.parse(localStorage.getItem('cv_results')||'[]');
let cloudStudents=[];
let registrations=JSON.parse(localStorage.getItem('cv_registrations')||'[]');
let student=JSON.parse(localStorage.getItem('cv_current_student')||'null');
let teacherUnlocked=sessionStorage.getItem('cv_teacher_unlocked')==='1';
let firebaseReady=false, app=null, db=null;

try{ app=initializeApp(firebaseConfig); db=getFirestore(app); firebaseReady=true; }catch(e){ console.warn(e); }

function $(id){return document.getElementById(id)}
function norm(s){return String(s||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ')}
function studentKey(names,paternal,maternal){return [norm(names),norm(paternal),norm(maternal)].join('|').replaceAll('/','-')}
function sectionFor(q){return SECTIONS.find(s=>q>=s.start&&q<=s.end)||SECTIONS[0]}
function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active')}
function save(){localStorage.setItem('cv_responses',JSON.stringify(responses));localStorage.setItem('cv_current_q',String(currentQ));localStorage.setItem('cv_current_page',String(currentPage));localStorage.setItem('cv_zoom',String(zoom));updateProgress();saveProgressCloud()}

function updateFirebaseStatus(){const el=$('firebaseStatus'); if(!el) return; el.textContent=firebaseReady?'Firebase conectado':'Firebase sin configurar';}
async function saveProgressCloud(){if(!firebaseReady||!student)return;try{await setDoc(doc(db,'exams',EXAM_ID,'students',student.studentKey),{student,status:'en_proceso',currentQ,currentPage,responses,updatedAt:serverTimestamp()},{merge:true})}catch(e){console.warn(e)}}
function updateProgress(){$('currentQuestionText').textContent='Reactivo '+currentQ+' de '+TOTAL;$('progressBar').style.width=Math.round((currentQ-1)/TOTAL*100)+'%'}
function applyZoom(){const img=$('pageImage'); if(!img)return; img.style.width=(zoom*100)+'%'; $('zoomLabel').textContent=Math.round(zoom*100)+'%'; localStorage.setItem('cv_zoom',String(zoom))}
function renderPage(){if(currentPage<1)currentPage=1;if(currentPage>TOTAL_PAGES)currentPage=TOTAL_PAGES;$('pageNumberLabel').textContent='Página '+currentPage+' de '+TOTAL_PAGES;$('pageImage').src='pages/page_'+String(currentPage).padStart(2,'0')+'.jpg';$('btnPrevPage').disabled=currentPage<=1;$('btnNextPage').disabled=currentPage>=TOTAL_PAGES;localStorage.setItem('cv_current_page',String(currentPage));applyZoom()}
function renderQuestion(){if(!student)return;if(currentQ<1)currentQ=1;if(currentQ>TOTAL)currentQ=TOTAL;let s=sectionFor(currentQ);$('studentDisplay').textContent=student.fullName+' | Tercero';$('currentSectionTitle').textContent=s.name+' | Reactivos '+s.start+'-'+s.end;$('qBadge').textContent='Reactivo '+currentQ;$('sectionBadge').textContent=s.name;$('sectionBadge').style.background=s.type==='mat'?'#edfff0':'#e9f4ff';$('sectionBadge').style.color=s.type==='mat'?'#11682b':'#0b3b78';let opts=$('answerOptions');opts.innerHTML='';LETTERS.forEach(l=>{let label=document.createElement('label');label.innerHTML=`<input type="radio" name="currentAnswer" value="${l}"><span class="circle"></span><span>Opción ${l}</span>`;let input=label.querySelector('input');input.checked=responses[currentQ]===l;input.onchange=()=>{responses[currentQ]=l;save()};opts.appendChild(label)});$('btnNextQuestion').classList.toggle('hidden',currentQ===TOTAL);$('btnFinish').classList.toggle('hidden',currentQ!==TOTAL);renderPage();updateProgress()}

$('btnPrevPage').onclick=()=>{if(currentPage>1){currentPage--;renderPage();saveProgressCloud()}};
$('btnNextPage').onclick=()=>{if(currentPage<TOTAL_PAGES){currentPage++;renderPage();saveProgressCloud()}};
$('zoomIn').onclick=()=>{zoom=Math.min(2.5,zoom+.15);applyZoom()};
$('zoomOut').onclick=()=>{zoom=Math.max(.7,zoom-.15);applyZoom()};
$('zoomReset').onclick=()=>{zoom=1;applyZoom()};

$('btnStartExam').onclick=async()=>{let names=$('studentNames').value.trim(),paternal=$('studentPaternal').value.trim(),maternal=$('studentMaternal').value.trim(),matricula=$('studentId').value.trim();$('registerError').textContent='';if(!names||!paternal||!maternal){$('registerError').textContent='Captura nombre(s), apellido paterno y apellido materno.';return}let keyStudent=studentKey(names,paternal,maternal);if(firebaseReady){try{let ref=doc(db,'exams',EXAM_ID,'students',keyStudent);let snap=await getDoc(ref);if(snap.exists()){$('registerError').textContent='Este estudiante ya fue registrado. No puede volver a ingresar.';return}student={names,paternal,maternal,fullName:[names,paternal,maternal].join(' '),grade:'Tercero',matricula,studentKey:keyStudent,startTime:new Date().toLocaleString()};await setDoc(ref,{student,status:'en_proceso',currentQ:1,currentPage:1,responses:{},createdAt:serverTimestamp(),updatedAt:serverTimestamp()})}catch(e){console.error(e);$('registerError').textContent='No se pudo registrar en Firebase.';return}}else{if(registrations.includes(keyStudent)){$('registerError').textContent='Este estudiante ya fue registrado en este dispositivo.';return}student={names,paternal,maternal,fullName:[names,paternal,maternal].join(' '),grade:'Tercero',matricula,studentKey:keyStudent,startTime:new Date().toLocaleString()};registrations.push(keyStudent);localStorage.setItem('cv_registrations',JSON.stringify(registrations))}localStorage.setItem('cv_current_student',JSON.stringify(student));responses={};currentQ=1;currentPage=1;localStorage.setItem('cv_responses','{}');localStorage.setItem('cv_current_q','1');localStorage.setItem('cv_current_page','1');showScreen('examScreen');renderQuestion()};

$('btnNextQuestion').onclick=()=>{if(!responses[currentQ]){alert('Selecciona una respuesta antes de avanzar.');return}if(currentQ<TOTAL){currentQ++;save();renderQuestion();window.scrollTo({top:0,behavior:'smooth'})}};

function countRanges(ranges, resp){let ok=0,total=0;ranges.forEach(([a,b])=>{for(let q=a;q<=b;q++){total++;if(key[q]&&resp[q]===key[q])ok++}});return {ok,total}}
function makeRecord(){let rec={Nombres:student?.names||'','Apellido paterno':student?.paternal||'','Apellido materno':student?.maternal||'','Nombre completo':student?.fullName||'',Grado:'Tercero',Matricula:student?.matricula||'','Inicio':student?.startTime||'','Finalización':new Date().toLocaleString()};let total=0;SECTIONS.forEach(s=>{let ok=0,answered=0;for(let q=s.start;q<=s.end;q++){if(responses[q])answered++;if(key[q]&&responses[q]===key[q])ok++}rec[s.name]=ok;rec[s.name+' respondidas']=answered;rec[s.name+' total']=s.end-s.start+1;total+=ok});let esp=countRanges(SPANISH_RANGES,responses),mat=countRanges(MATH_RANGES,responses);rec.Español=esp.ok;rec['Español total']=esp.total;rec.Matemáticas=mat.ok;rec['Matemáticas total']=mat.total;rec.Total=total;rec['Total reactivos']=TOTAL;rec.Porcentaje=Math.round(total/TOTAL*10000)/100;for(let q=1;q<=TOTAL;q++)rec['R'+q]=responses[q]||'';return rec}
function showStudentResults(rec){let box=$('studentResults');let rows=`<tr><td>Español</td><td>${rec.Español} / ${rec['Español total']}</td><td>${Math.round(rec.Español/rec['Español total']*100)}%</td></tr><tr><td>Matemáticas</td><td>${rec.Matemáticas} / ${rec['Matemáticas total']}</td><td>${Math.round(rec.Matemáticas/rec['Matemáticas total']*100)}%</td></tr>`;box.innerHTML=`<div class="result-summary"><strong>${rec.Total} / ${rec['Total reactivos']}</strong><span>Porcentaje: ${rec.Porcentaje}%</span></div><table class="result-table"><thead><tr><th>Área</th><th>Aciertos</th><th>%</th></tr></thead><tbody>${rows}</tbody></table>`}

async function finishExam(force=false){if(!force && !responses[currentQ]){alert('Selecciona una respuesta antes de finalizar.');return}if(force && !confirm('¿Deseas finalizar el examen? Las preguntas sin responder se calificarán como incorrectas.'))return;let rec=makeRecord();results.push(rec);localStorage.setItem('cv_results',JSON.stringify(results));if(firebaseReady&&student){try{await setDoc(doc(db,'exams',EXAM_ID,'students',student.studentKey),{student,status:'finalizado',currentQ,currentPage,responses,result:rec,finishedAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true})}catch(e){console.error(e)}}showStudentResults(rec);localStorage.removeItem('cv_current_student');showScreen('finishedScreen')}
$('btnFinish').onclick=()=>finishExam(false);
$('btnFinishEarly').onclick=()=>finishExam(true);

function requireTeacher(action){if(teacherUnlocked){action();return}$('loginDialog').showModal();window.pendingTeacherAction=action}
$('btnTeacherLogin').onclick=()=>requireTeacher(async()=>{$('teacherDialog').showModal();await loadStudents();showTeacherPanel('dashboardPanel')});
$('closeLogin').onclick=()=>$('loginDialog').close();
$('loginTeacher').onclick=async()=>{if($('teacherPassword').value===TEACHER_PASS){teacherUnlocked=true;sessionStorage.setItem('cv_teacher_unlocked','1');$('teacherPassword').value='';$('loginDialog').close();updateFirebaseStatus();if(window.pendingTeacherAction)await window.pendingTeacherAction();else $('teacherDialog').showModal()}else alert('Contraseña incorrecta.')};

function resultFromData(d){if(d.result)return d.result;let oldR=responses,oldS=student;responses=d.responses||{};student=d.student||null;let r=makeRecord();responses=oldR;student=oldS;return r}
async function loadStudents(){if(firebaseReady){let snap=await getDocs(collection(db,'exams',EXAM_ID,'students'));cloudStudents=[];snap.forEach(d=>cloudStudents.push({id:d.id,data:d.data()}));results=cloudStudents.filter(x=>x.data.result).map(x=>x.data.result);localStorage.setItem('cv_results',JSON.stringify(results))}else{cloudStudents=results.map((r,i)=>({id:'local_'+i,data:{student:{fullName:r['Nombre completo']},status:'local',result:r}}))}renderTeacherData()}
function renderTeacherData(){let tbody=$('studentsTableBody');if(!tbody)return;let finished=0,progress=0,totalPct=0,totalEsp=0,totalMat=0;tbody.innerHTML='';cloudStudents.forEach(item=>{let d=item.data,rec=resultFromData(d),st=d.status||'en_proceso';if(st==='finalizado')finished++;else progress++;totalPct+=rec.Porcentaje||0;totalEsp+=rec.Español||0;totalMat+=rec.Matemáticas||0;let tr=document.createElement('tr');tr.innerHTML=`<td>${d.student?.fullName||rec['Nombre completo']||item.id}</td><td><span class="badge ${st==='finalizado'?'done':'progress'}">${st}</span></td><td>${rec.Español||0} / 50</td><td>${rec.Matemáticas||0} / 61</td><td>${rec.Total||0} / 111</td><td><div class="row-actions"><button class="smallBtn secondary" data-reset="${item.id}">Reiniciar</button><button class="smallBtn danger" data-delete="${item.id}">Borrar</button></div></td>`;tbody.appendChild(tr)});let n=cloudStudents.length||1;$('statRegistered').textContent=cloudStudents.length;$('statFinished').textContent=finished;$('statProgress').textContent=progress;$('statAverage').textContent=Math.round(totalPct/n)+'%';$('statSpanish').textContent=(Math.round(totalEsp/n*10)/10)+' / 50';$('statMath').textContent=(Math.round(totalMat/n*10)/10)+' / 61';document.querySelectorAll('[data-reset]').forEach(b=>b.onclick=()=>resetStudent(b.dataset.reset));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteStudent(b.dataset.delete))}
async function resetStudent(id){if(!confirm('¿Reiniciar el examen de este estudiante?'))return;if(firebaseReady){await deleteDoc(doc(db,'exams',EXAM_ID,'students',id));await loadStudents()}}
async function deleteStudent(id){if(!confirm('¿Borrar definitivamente este registro?'))return;if(firebaseReady){await deleteDoc(doc(db,'exams',EXAM_ID,'students',id));await loadStudents()}}
function exportExcel(){let data=results.length?results:cloudStudents.map(x=>resultFromData(x.data));if(!data.length){alert('No hay resultados para exportar.');return}let wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(data);XLSX.utils.book_append_sheet(wb,ws,'Resultados');XLSX.writeFile(wb,'Resultados_Examen_Colegio_Valenciana.xlsx')}
function buildKey(){let grid=$('answerKeyGrid');grid.innerHTML='';for(let q=1;q<=TOTAL;q++){let d=document.createElement('div');d.className='keyItem';d.innerHTML=`<b>Reactivo ${q}</b><select data-key="${q}"><option value="">Sin clave</option>${LETTERS.map(l=>`<option value="${l}">${l}</option>`).join('')}</select>`;grid.appendChild(d);d.querySelector('select').value=key[q]||''}}
function showTeacherPanel(id){document.querySelectorAll('.teacher-panel').forEach(p=>p.classList.remove('active'));document.querySelectorAll('.menu-item').forEach(m=>m.classList.remove('active'));$(id).classList.add('active');document.querySelector(`[data-panel="${id}"]`)?.classList.add('active');$('teacherPanelTitle').textContent={dashboardPanel:'Dashboard',studentsPanel:'Registros',keyPanel:'Clave de respuestas',toolsPanel:'Herramientas'}[id]||'Panel docente';renderTeacherData()}
document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>showTeacherPanel(b.dataset.panel));
$('btnRefreshStudents').onclick=()=>requireTeacher(loadStudents);$('btnDownloadCloud').onclick=()=>requireTeacher(loadStudents);$('btnExport').onclick=()=>requireTeacher(exportExcel);$('btnQr').onclick=()=>requireTeacher(()=>{$('qrUrl').value=location.protocol.startsWith('http')?location.href.split('#')[0]:'';$('qrDialog').showModal()});$('closeTeacher').onclick=()=>$('teacherDialog').close();$('toggleKey').onclick=()=>$('answerKeyGrid').classList.toggle('hidden');$('saveKey').onclick=()=>{document.querySelectorAll('[data-key]').forEach(s=>{if(s.value)key[s.dataset.key]=s.value});alert('Clave guardada localmente.')};$('clearResults').onclick=()=>{results=[];registrations=[];localStorage.setItem('cv_results','[]');localStorage.setItem('cv_registrations','[]');alert('Resultados locales borrados.')};$('logoutTeacher').onclick=()=>{teacherUnlocked=false;sessionStorage.removeItem('cv_teacher_unlocked');$('teacherDialog').close()};
$('closeQr').onclick=()=>$('qrDialog').close();$('generateQr').onclick=()=>{let url=$('qrUrl').value.trim();if(!url){alert('Pega primero el enlace público del examen.');return}let src='https://api.qrserver.com/v1/create-qr-code/?size=600x600&data='+encodeURIComponent(url);$('qrImage').src=src;$('downloadQr').href=src;$('downloadQr').style.display='inline-block'};

buildKey();updateFirebaseStatus();if(student){showScreen('examScreen');renderQuestion()}else showScreen('registrationScreen');
