import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
import { getFirestore, doc, getDoc, setDoc, deleteDoc, collection, getDocs, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
import { firebaseConfig, EXAM_ID } from "./firebase-config.js";

const SECTIONS=[{"name":"Español I","start":1,"end":9,"type":"esp"},{"name":"Matemáticas I","start":10,"end":30,"type":"mat"},{"name":"Español II","start":31,"end":47,"type":"esp"},{"name":"Matemáticas II","start":48,"end":67,"type":"mat"},{"name":"Español III","start":68,"end":82,"type":"esp"},{"name":"Matemáticas III","start":83,"end":102,"type":"mat"},{"name":"Español IV","start":103,"end":111,"type":"esp"}];
const TOTAL=111,TOTAL_PAGES=35,LETTERS=['A','B','C','D'],TEACHER_PASS='valenciana2026';
const SPANISH_RANGES=[[1,9],[31,47],[68,82],[103,111]], MATH_RANGES=[[10,30],[48,67],[83,102]];
let key={"1":"B","2":"C","3":"C","4":"D","5":"B","6":"A","7":"B","8":"D","9":"B","10":"A","11":"A","12":"A","13":"D","14":"B","15":"C","16":"A","17":"C","18":"C","19":"B","20":"C","21":"B","22":"B","23":"D","24":"A","25":"A","26":"D","27":"D","28":"B","29":"D","30":"B","31":"D","32":"B","33":"A","34":"A","35":"D","36":"B","37":"B","38":"D","39":"C","40":"A","41":"C","42":"D","43":"B","44":"C","45":"D","46":"A","47":"A","48":"B","49":"A","50":"A","51":"D","52":"C","53":"A","54":"B","55":"C","56":"A","57":"C","58":"A","59":"C","60":"A","61":"D","62":"C","63":"D","64":"A","65":"C","66":"C","67":"B","68":"D","69":"B","70":"A","71":"D","72":"B","73":"C","74":"A","75":"D","76":"D","77":"A","78":"D","79":"C","80":"B","81":"D","82":"A","83":"B","84":"B","85":"B","86":"D","87":"A","88":"C","89":"C","90":"B","91":"B","92":"C","93":"A","94":"D","95":"B","96":"C","97":"A","98":"C","99":"D","100":"C","101":"C","102":"C","103":"D","104":"D","105":"C","106":"D","107":"B","108":"B","109":"C","110":"B","111":"C"};
Object.assign(key,JSON.parse(localStorage.getItem('cv_answer_key')||'{}'));
let currentQ=parseInt(localStorage.getItem('cv_current_q')||'1'),currentPage=parseInt(localStorage.getItem('cv_current_page')||'1'),zoom=parseFloat(localStorage.getItem('cv_zoom')||'1');
let responses=JSON.parse(localStorage.getItem('cv_responses')||'{}'),results=JSON.parse(localStorage.getItem('cv_results')||'[]'),registrations=JSON.parse(localStorage.getItem('cv_registrations')||'[]'),student=JSON.parse(localStorage.getItem('cv_current_student')||'null'),cloudStudents=[],teacherUnlocked=sessionStorage.getItem('cv_teacher_unlocked')==='1';
let firebaseReady=false,app=null,db=null;
try{if(firebaseConfig?.apiKey&&!firebaseConfig.apiKey.includes('PEGAR_')){app=initializeApp(firebaseConfig);db=getFirestore(app);firebaseReady=true;}}catch(e){console.warn(e)}
function $(id){return document.getElementById(id)}
function norm(s){return String(s||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ')}
function studentKey(n,p,m){return [norm(n),norm(p),norm(m)].join('|').replaceAll('/','-')}
function sectionFor(q){return SECTIONS.find(s=>q>=s.start&&q<=s.end)||SECTIONS[0]}
function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active')}
function updateFirebaseStatus(){let e=$('firebaseStatus');if(e){e.textContent=firebaseReady?'Firebase conectado':'Firebase sin configurar';e.style.color=firebaseReady?'#c9ffd7':'#ffd2d2'}}
function updateProgress(){$('currentQuestionText').textContent='Reactivo '+currentQ+' de '+TOTAL;$('progressBar').style.width=Math.round((currentQ-1)/TOTAL*100)+'%'}
function applyZoom(){let img=$('pageImage');if(!img)return;img.style.width=(zoom*100)+'%';$('zoomLabel').textContent=Math.round(zoom*100)+'%';localStorage.setItem('cv_zoom',zoom)}
function renderPage(){currentPage=Math.max(1,Math.min(TOTAL_PAGES,currentPage));$('pageNumberLabel').textContent='Página '+currentPage+' de '+TOTAL_PAGES;$('pageImage').src='pages/page_'+String(currentPage).padStart(2,'0')+'.jpg';$('btnPrevPage').disabled=currentPage<=1;$('btnNextPage').disabled=currentPage>=TOTAL_PAGES;localStorage.setItem('cv_current_page',currentPage);applyZoom()}
function save(){localStorage.setItem('cv_responses',JSON.stringify(responses));localStorage.setItem('cv_current_q',currentQ);localStorage.setItem('cv_current_page',currentPage);updateProgress();saveProgressCloud()}
async function saveProgressCloud(){if(!firebaseReady||!student)return;try{await setDoc(doc(db,'exams',EXAM_ID,'students',student.studentKey),{student,status:'en_proceso',currentQ,currentPage,responses,updatedAt:serverTimestamp()},{merge:true})}catch(e){console.warn(e)}}
function renderQuestion(){if(!student)return;currentQ=Math.max(1,Math.min(TOTAL,currentQ));let s=sectionFor(currentQ);$('studentDisplay').textContent=student.fullName+' | Tercero';$('currentSectionTitle').textContent=s.name+' | Reactivos '+s.start+'-'+s.end;$('qBadge').textContent='Reactivo '+currentQ;$('sectionBadge').textContent=s.name;$('sectionBadge').style.background=s.type==='mat'?'#edfff0':'#e9f4ff';$('sectionBadge').style.color=s.type==='mat'?'#11682b':'#0b3b78';let opts=$('answerOptions');opts.innerHTML='';LETTERS.forEach(l=>{let lab=document.createElement('label');lab.innerHTML=`<input type="radio" name="currentAnswer" value="${l}"><span class="circle"></span><span>Opción ${l}</span>`;let inp=lab.querySelector('input');inp.checked=responses[currentQ]===l;inp.onchange=()=>{responses[currentQ]=l;save()};opts.appendChild(lab)});$('btnNextQuestion').classList.toggle('hidden',currentQ===TOTAL);$('btnFinish').classList.toggle('hidden',currentQ!==TOTAL);renderPage();updateProgress()}
$('btnPrevPage').onclick=()=>{if(currentPage>1){currentPage--;renderPage();saveProgressCloud()}};$('btnNextPage').onclick=()=>{if(currentPage<TOTAL_PAGES){currentPage++;renderPage();saveProgressCloud()}};$('zoomIn').onclick=()=>{zoom=Math.min(2.5,zoom+.15);applyZoom()};$('zoomOut').onclick=()=>{zoom=Math.max(.7,zoom-.15);applyZoom()};$('zoomReset').onclick=()=>{zoom=1;applyZoom()};
$('btnStartExam').onclick=async()=>{let names=$('studentNames').value.trim(),paternal=$('studentPaternal').value.trim(),maternal=$('studentMaternal').value.trim(),matricula=$('studentId').value.trim();$('registerError').textContent='';if(!names||!paternal||!maternal){$('registerError').textContent='Captura nombre(s), apellido paterno y apellido materno.';return}let k=studentKey(names,paternal,maternal);if(firebaseReady){try{let ref=doc(db,'exams',EXAM_ID,'students',k),snap=await getDoc(ref);if(snap.exists()){$('registerError').textContent='Este estudiante ya fue registrado. No puede volver a ingresar.';return}student={names,paternal,maternal,fullName:[names,paternal,maternal].join(' '),grade:'Tercero',matricula,studentKey:k,startTime:new Date().toLocaleString()};await setDoc(ref,{student,status:'en_proceso',currentQ:1,currentPage:1,responses:{},createdAt:serverTimestamp(),updatedAt:serverTimestamp()})}catch(e){console.error(e);$('registerError').textContent='No se pudo registrar en Firebase.';return}}else{if(registrations.includes(k)){$('registerError').textContent='Este estudiante ya fue registrado en este dispositivo.';return}student={names,paternal,maternal,fullName:[names,paternal,maternal].join(' '),grade:'Tercero',matricula,studentKey:k,startTime:new Date().toLocaleString()};registrations.push(k);localStorage.setItem('cv_registrations',JSON.stringify(registrations))}localStorage.setItem('cv_current_student',JSON.stringify(student));responses={};currentQ=1;currentPage=1;localStorage.setItem('cv_responses','{}');localStorage.setItem('cv_current_q','1');localStorage.setItem('cv_current_page','1');showScreen('examScreen');renderQuestion()};
$('btnNextQuestion').onclick=()=>{if(!responses[currentQ]){alert('Selecciona una respuesta antes de avanzar.');return}if(currentQ<TOTAL){currentQ++;save();renderQuestion();scrollTo({top:0,behavior:'smooth'})}};
function countRanges(ranges,resp){let ok=0,total=0;ranges.forEach(([a,b])=>{for(let q=a;q<=b;q++){total++;if(key[q]&&resp[q]===key[q])ok++}});return{ok,total}}
function scoreRecord(){let rec={Nombres:student?.names||'','Apellido paterno':student?.paternal||'','Apellido materno':student?.maternal||'','Nombre completo':student?.fullName||'',Grado:'Tercero',Matricula:student?.matricula||'',Inicio:student?.startTime||'',Finalización:new Date().toLocaleString()};let total=0;SECTIONS.forEach(s=>{let ok=0,answered=0;for(let q=s.start;q<=s.end;q++){if(responses[q])answered++;if(key[q]&&responses[q]===key[q])ok++}rec[s.name]=ok;rec[s.name+' respondidas']=answered;rec[s.name+' total']=s.end-s.start+1;total+=ok});let esp=countRanges(SPANISH_RANGES,responses),mat=countRanges(MATH_RANGES,responses);rec.Español=esp.ok;rec['Español total']=esp.total;rec.Matemáticas=mat.ok;rec['Matemáticas total']=mat.total;rec.Total=total;rec['Total reactivos']=TOTAL;rec.Porcentaje=Math.round(total/TOTAL*10000)/100;for(let q=1;q<=TOTAL;q++)rec['R'+q]=responses[q]||'';return rec}
function showStudentResults(rec){let box=$('studentResults');let rows=`<tr><td>Español</td><td>${rec.Español} / ${rec['Español total']}</td><td>${Math.round(rec.Español/rec['Español total']*100)}%</td></tr><tr><td>Matemáticas</td><td>${rec.Matemáticas} / ${rec['Matemáticas total']}</td><td>${Math.round(rec.Matemáticas/rec['Matemáticas total']*100)}%</td></tr>`;box.innerHTML=`<div class="result-summary"><strong>${rec.Total} / ${rec['Total reactivos']}</strong><span>Porcentaje: ${rec.Porcentaje}%</span></div><table class="result-table"><thead><tr><th>Área</th><th>Aciertos</th><th>%</th></tr></thead><tbody>${rows}</tbody></table>`}
$('btnFinish').onclick=async()=>{if(!responses[currentQ]){alert('Selecciona una respuesta antes de finalizar.');return}let falt=[];for(let q=1;q<=TOTAL;q++)if(!responses[q])falt.push(q);if(falt.length&&!confirm('Faltan reactivos por responder: '+falt.join(', ')+'. ¿Deseas finalizar de todos modos?'))return;let rec=scoreRecord();results.push(rec);localStorage.setItem('cv_results',JSON.stringify(results));if(firebaseReady&&student){try{await setDoc(doc(db,'exams',EXAM_ID,'students',student.studentKey),{student,status:'finalizado',currentQ,currentPage,responses,result:rec,finishedAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true})}catch(e){alert('Resultado guardado localmente, pero no enviado a Firebase.')}}showStudentResults(rec);localStorage.removeItem('cv_current_student');showScreen('finishedScreen')};
function requireTeacher(action){if(teacherUnlocked){action();return}$('loginDialog').showModal();window.pendingTeacherAction=action}
$('btnTeacherLogin').onclick=()=>requireTeacher(async()=>{$('teacherDialog').showModal();await loadCloudStudents();showTeacherPanel('dashboardPanel')});$('closeLogin').onclick=()=>$('loginDialog').close();$('loginTeacher').onclick=async()=>{if($('teacherPassword').value===TEACHER_PASS){teacherUnlocked=true;sessionStorage.setItem('cv_teacher_unlocked','1');$('teacherPassword').value='';$('loginDialog').close();updateFirebaseStatus();if(window.pendingTeacherAction)await window.pendingTeacherAction();else $('teacherDialog').showModal()}else alert('Contraseña incorrecta.')};
function resultFromData(data){if(data.result)return data.result;let oldR=responses,oldS=student;responses=data.responses||{};student=data.student||null;let rec=scoreRecord();responses=oldR;student=oldS;return rec}
async function loadCloudStudents(){if(!firebaseReady){cloudStudents=results.map((r,i)=>({id:'local_'+i,data:{student:{fullName:r['Nombre completo']||'',studentKey:'local_'+i},status:'local',result:r}}));renderTeacherData();return}try{let snap=await getDocs(collection(db,'exams',EXAM_ID,'students'));cloudStudents=[];snap.forEach(d=>cloudStudents.push({id:d.id,data:d.data()}));results=cloudStudents.filter(x=>x.data.result).map(x=>x.data.result);localStorage.setItem('cv_results',JSON.stringify(results));renderTeacherData()}catch(e){console.error(e);alert('No se pudieron cargar registros de Firebase.')}}
function renderTeacherData(){let tbody=$('studentsTableBody');if(!tbody)return;let finished=0,progress=0,totalPct=0,totalEsp=0,totalMat=0;tbody.innerHTML='';cloudStudents.forEach(item=>{let d=item.data,rec=resultFromData(d),st=d.status||'en_proceso';if(st==='finalizado')finished++;else progress++;totalPct+=rec.Porcentaje||0;totalEsp+=rec.Español||0;totalMat+=rec.Matemáticas||0;let tr=document.createElement('tr');tr.innerHTML=`<td>${d.student?.fullName||rec['Nombre completo']||item.id}</td><td><span class="badge ${st==='finalizado'?'done':'progress'}">${st}</span></td><td>${rec.Español||0} / 50</td><td>${rec.Matemáticas||0} / 61</td><td>${rec.Total||0} / 111</td><td><div class="row-actions"><button class="smallBtn secondary" data-reset="${item.id}">Reiniciar</button><button class="smallBtn danger" data-delete="${item.id}">Borrar</button></div></td>`;tbody.appendChild(tr)});let n=cloudStudents.length||1;$('statRegistered').textContent=cloudStudents.length;$('statFinished').textContent=finished;$('statProgress').textContent=progress;$('statAverage').textContent=Math.round(totalPct/n)+'%';$('statSpanish').textContent=(Math.round(totalEsp/n*10)/10)+' / 50';$('statMath').textContent=(Math.round(totalMat/n*10)/10)+' / 61';document.querySelectorAll('[data-reset]').forEach(b=>b.onclick=()=>resetStudent(b.dataset.reset));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteStudent(b.dataset.delete))}
async function resetStudent(id){if(!firebaseReady)return alert('Solo disponible con Firebase.');if(confirm('¿Reiniciar el examen de este estudiante?')){await deleteDoc(doc(db,'exams',EXAM_ID,'students',id));await loadCloudStudents()}}
async function deleteStudent(id){if(!firebaseReady)return alert('Solo disponible con Firebase.');if(confirm('¿Borrar definitivamente este registro?')){await deleteDoc(doc(db,'exams',EXAM_ID,'students',id));await loadCloudStudents()}}
function exportExcel(){let data=results.length?results:cloudStudents.map(x=>resultFromData(x.data));if(!data.length)return alert('No hay resultados.');let wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(data);XLSX.utils.book_append_sheet(wb,ws,'Resultados');XLSX.writeFile(wb,'Resultados_Examen_Colegio_Valenciana.xlsx')}
function buildKey(){let grid=$('answerKeyGrid');grid.innerHTML='';for(let q=1;q<=TOTAL;q++){let d=document.createElement('div');d.className='keyItem';d.innerHTML=`<b>Reactivo ${q}</b><select data-key="${q}"><option value="">Sin clave</option>${LETTERS.map(l=>`<option value="${l}">${l}</option>`).join('')}</select>`;grid.appendChild(d);d.querySelector('select').value=key[q]||''}}
function showTeacherPanel(id){document.querySelectorAll('.teacher-panel').forEach(p=>p.classList.remove('active'));document.querySelectorAll('.menu-item').forEach(m=>m.classList.remove('active'));$(id).classList.add('active');document.querySelector(`[data-panel="${id}"]`)?.classList.add('active');$('teacherPanelTitle').textContent={dashboardPanel:'Dashboard',studentsPanel:'Registros',keyPanel:'Clave de respuestas',toolsPanel:'Herramientas'}[id]||'Panel docente';renderTeacherData()}
document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>showTeacherPanel(b.dataset.panel));$('btnRefreshStudents').onclick=()=>requireTeacher(loadCloudStudents);$('btnDownloadCloud').onclick=()=>requireTeacher(loadCloudStudents);$('btnExport').onclick=()=>requireTeacher(exportExcel);$('btnQr').onclick=()=>requireTeacher(()=>{$('qrUrl').value=location.protocol.startsWith('http')?location.href.split('#')[0]:'';$('qrDialog').showModal()});$('closeTeacher').onclick=()=>$('teacherDialog').close();$('toggleKey').onclick=()=>$('answerKeyGrid').classList.toggle('hidden');$('saveKey').onclick=()=>{document.querySelectorAll('[data-key]').forEach(s=>{if(s.value)key[s.dataset.key]=s.value;else delete key[s.dataset.key]});localStorage.setItem('cv_answer_key',JSON.stringify(key));alert('Clave guardada localmente.')};$('clearResults').onclick=()=>{if(confirm('¿Borrar resultados locales?')){results=[];registrations=[];localStorage.setItem('cv_results','[]');localStorage.setItem('cv_registrations','[]');alert('Resultados locales borrados.')}};$('logoutTeacher').onclick=()=>{teacherUnlocked=false;sessionStorage.removeItem('cv_teacher_unlocked');$('teacherDialog').close();alert('Acceso docente cerrado.')};$('closeQr').onclick=()=>$('qrDialog').close();$('generateQr').onclick=()=>{let url=$('qrUrl').value.trim();if(!url)return alert('Pega primero el enlace público.');let src='https://api.qrserver.com/v1/create-qr-code/?size=600x600&data='+encodeURIComponent(url);$('qrImage').src=src;$('downloadQr').href=src;$('downloadQr').style.display='inline-block'};
buildKey();updateFirebaseStatus();if(student){showScreen('examScreen');renderQuestion()}else showScreen('registrationScreen');
