const SECTIONS=[{"name": "Español I", "start": 1, "end": 9, "type": "esp", "page": 3}, {"name": "Matemáticas I", "start": 10, "end": 30, "type": "mat", "page": 5}, {"name": "Español II", "start": 31, "end": 47, "type": "esp", "page": 10}, {"name": "Matemáticas II", "start": 48, "end": 67, "type": "mat", "page": 14}, {"name": "Español III", "start": 68, "end": 82, "type": "esp", "page": 21}, {"name": "Matemáticas III", "start": 83, "end": 102, "type": "mat", "page": 26}, {"name": "Español IV", "start": 103, "end": 111, "type": "esp", "page": 31}],TOTAL=111,LETTERS=['A','B','C','D'],TEACHER_PASS='valenciana2026';
let currentQ=parseInt(localStorage.getItem('cv_current_q')||'1',10),responses=JSON.parse(localStorage.getItem('cv_responses')||'{}'),key=JSON.parse(localStorage.getItem('cv_answer_key')||'{}'),results=JSON.parse(localStorage.getItem('cv_results')||'[]'),teacherUnlocked=sessionStorage.getItem('cv_teacher_unlocked')==='1';
function $(id){return document.getElementById(id)}function sectionFor(q){return SECTIONS.find(s=>q>=s.start&&q<=s.end)||SECTIONS[0]}
function save(){localStorage.setItem('cv_responses',JSON.stringify(responses));localStorage.setItem('cv_current_q',String(currentQ));$('saved').textContent='Guardado '+new Date().toLocaleTimeString();updateCounts()}
function updateCounts(){$('answered').textContent=Object.values(responses).filter(v=>v).length;$('progressNum').textContent=currentQ;document.querySelectorAll('.navBtn').forEach((b,i)=>{let s=SECTIONS[i],c=0;for(let q=s.start;q<=s.end;q++)if(responses[q])c++;b.querySelector('.count').textContent=`${c}/${s.end-s.start+1}`;b.classList.toggle('active',currentQ>=s.start&&currentQ<=s.end)})}
function buildNav(){let nav=$('sectionNav');nav.innerHTML='';SECTIONS.forEach(s=>{let nb=document.createElement('div');nb.className='navBtn '+(s.type==='mat'?'mat':'');nb.innerHTML=`<span>${s.name}</span><span class="count">0/${s.end-s.start+1}</span>`;nav.appendChild(nb)})}
function renderQuestion(){if(currentQ<1)currentQ=1;if(currentQ>TOTAL)currentQ=TOTAL;let s=sectionFor(currentQ);$('currentSectionTitle').textContent=s.name+' | Reactivos '+s.start+'-'+s.end;$('currentQuestionText').textContent='Reactivo actual: '+currentQ+' de '+TOTAL;$('qBadge').textContent='Reactivo '+currentQ;$('sectionBadge').textContent=s.name;$('sectionBadge').style.background=s.type==='mat'?'#edfff0':'#e9f4ff';$('sectionBadge').style.color=s.type==='mat'?'#11682b':'#0b3b78';$('pdfFrame').src='cuadernillo_rima.pdf#page='+s.page+'&toolbar=0&navpanes=0&scrollbar=0&view=FitH';let opts=$('answerOptions');opts.innerHTML='';LETTERS.forEach(l=>{let label=document.createElement('label');label.innerHTML=`<input type="radio" name="currentAnswer" value="${l}"><span class="circle"></span><span>Opción ${l}</span>`;let input=label.querySelector('input');input.checked=responses[currentQ]===l;input.onchange=()=>{responses[currentQ]=l;save()};opts.appendChild(label)});$('btnNextQuestion').classList.toggle('hidden',currentQ===TOTAL);$('btnFinish').classList.toggle('hidden',currentQ!==TOTAL);updateCounts()}
$('btnNextQuestion').onclick=()=>{if(!responses[currentQ]){alert('Selecciona una respuesta antes de avanzar.');return}if(currentQ<TOTAL){currentQ++;save();renderQuestion();window.scrollTo({top:0,behavior:'smooth'})}};
function scoreRecord(){let rec={Nombre:$('studentName').value.trim(),Grado:'Tercero',Matricula:$('studentId').value.trim(),Fecha:new Date().toLocaleString()},total=0;SECTIONS.forEach(s=>{let ok=0,answered=0;for(let q=s.start;q<=s.end;q++){if(responses[q])answered++;if(key[q]&&responses[q]===key[q])ok++}rec[s.name]=ok;rec[s.name+' respondidas']=answered;rec[s.name+' total']=s.end-s.start+1;total+=ok});rec.Total=total;rec['Total reactivos']=TOTAL;rec.Porcentaje=Math.round(total/TOTAL*10000)/100;for(let q=1;q<=TOTAL;q++)rec['R'+q]=responses[q]||'';return rec}
$('btnFinish').onclick=()=>{if(!$('studentName').value.trim()){alert('Escribe el nombre del alumno.');return}if(!responses[currentQ]){alert('Selecciona una respuesta antes de finalizar.');return}let faltantes=[];for(let q=1;q<=TOTAL;q++)if(!responses[q])faltantes.push(q);if(faltantes.length&&!confirm('Faltan reactivos por responder: '+faltantes.join(', ')+'. ¿Deseas finalizar de todos modos?'))return;let rec=scoreRecord();results.push(rec);localStorage.setItem('cv_results',JSON.stringify(results));alert('Resultado guardado.')}; 
function requireTeacher(action){if(teacherUnlocked){action();return}$('loginDialog').showModal();window.pendingTeacherAction=action}
$('btnTeacherLogin').onclick=()=>requireTeacher(()=>$('teacherDialog').showModal());
$('closeLogin').onclick=()=>$('loginDialog').close();
$('loginTeacher').onclick=()=>{if($('teacherPassword').value===TEACHER_PASS){teacherUnlocked=true;sessionStorage.setItem('cv_teacher_unlocked','1');$('teacherPassword').value='';$('loginDialog').close();if(window.pendingTeacherAction)window.pendingTeacherAction();else $('teacherDialog').showModal()}else alert('Contraseña incorrecta.')}; 
function exportExcel(){let data=results.length?results:[scoreRecord()];if(window.XLSX){let wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(data);XLSX.utils.book_append_sheet(wb,ws,'Resultados');XLSX.writeFile(wb,'Resultados_Examen_Colegio_Valenciana.xlsx')}else{let headers=Object.keys(data[0]),csv=[headers.join(',')].concat(data.map(r=>headers.map(h=>'"'+String(r[h]??'').replaceAll('"','""')+'"').join(','))).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='Resultados_Examen_Colegio_Valenciana.csv';a.click()}}
function buildKey(){let grid=$('answerKeyGrid');grid.innerHTML='';for(let q=1;q<=TOTAL;q++){let d=document.createElement('div');d.className='keyItem';d.innerHTML=`<b>Reactivo ${q}</b><select data-key="${q}"><option value="">Sin clave</option>${LETTERS.map(l=>`<option value="${l}">${l}</option>`).join('')}</select>`;grid.appendChild(d);d.querySelector('select').value=key[q]||''}}
$('btnExport').onclick=()=>requireTeacher(exportExcel);$('btnQr').onclick=()=>requireTeacher(()=>{$('qrUrl').value=location.protocol.startsWith('http')?location.href.split('#')[0]:'';$('qrDialog').showModal()});
$('closeTeacher').onclick=()=>$('teacherDialog').close();$('saveKey').onclick=()=>{document.querySelectorAll('[data-key]').forEach(s=>{if(s.value)key[s.dataset.key]=s.value;else delete key[s.dataset.key]});localStorage.setItem('cv_answer_key',JSON.stringify(key));alert('Clave guardada.')};$('clearResults').onclick=()=>{if(confirm('¿Borrar resultados guardados en este dispositivo?')){results=[];localStorage.setItem('cv_results','[]')}};$('resetExam').onclick=()=>{if(confirm('¿Reiniciar el examen actual?')){responses={};currentQ=1;localStorage.setItem('cv_responses','{}');localStorage.setItem('cv_current_q','1');renderQuestion()}};$('logoutTeacher').onclick=()=>{teacherUnlocked=false;sessionStorage.removeItem('cv_teacher_unlocked');$('teacherDialog').close();alert('Acceso docente cerrado.')}; 
$('closeQr').onclick=()=>$('qrDialog').close();$('generateQr').onclick=()=>{let url=$('qrUrl').value.trim();if(!url){alert('Pega primero el enlace público del examen.');return}let src='https://api.qrserver.com/v1/create-qr-code/?size=600x600&data='+encodeURIComponent(url);$('qrImage').src=src;$('downloadQr').href=src;$('downloadQr').style.display='inline-block'};
buildNav();buildKey();renderQuestion();
